### ISSUE TITLE
Assign Datatypes lens does not work with int target type

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/vizier-scala#101]
- to reproduce setup a project and load some data
- create an assign data type lense and choose 32 bit integer (other data types that I've tried seem to work, I didn't try all)

```
An internal error occurred: Failed to convert the JSON string 'int' to a data type.
```

```
20:36:22.315 [ForkJoinPool-1-worker-3] TRACE info.vizierdb.viztrails.Scheduler$ - About to Process [Assign Datatypes](dataset: "r", schema: <0,short>; <1,int>; <2,long>) <- (SCOPE: { r -> 137 })
java.lang.IllegalArgumentException: Failed to convert the JSON string 'int' to a data type.
	at org.apache.spark.sql.types.DataType$.$anonfun$nameToType$1(DataType.scala:151)
	at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:589)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:72)
	at org.apache.spark.sql.types.DataType$.nameToType(DataType.scala:150)
	at org.apache.spark.sql.types.DataType$.parseDataType(DataType.scala:165)
	at org.apache.spark.sql.types.DataType$.fromJson(DataType.scala:135)
	at org.mimirdb.spark.SparkPrimitive$$anon$1.reads(SparkPrimitive.scala:147)
	at org.mimirdb.spark.SparkPrimitive$$anon$1.reads(SparkPrimitive.scala:147)
	at play.api.libs.json.Format$$anon$6.reads(Format.scala:62)
	at play.api.libs.json.DefaultReads.$anonfun$mapReads$3(Reads.scala:565)
	at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:187)
	at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:185)
	at scala.collection.immutable.Map$Map3.foreach(Map.scala:331)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:189)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:184)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
	at play.api.libs.json.DefaultReads.$anonfun$mapReads$1(Reads.scala:562)
	at play.api.libs.json.Reads$$anon$6.reads(Reads.scala:222)
	at play.api.libs.json.JsValue.validate(JsValue.scala:17)
	at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
	at play.api.libs.json.JsObject.validate(JsValue.scala:121)
	at play.api.libs.json.JsReadable.asOpt(JsReadable.scala:18)
	at play.api.libs.json.JsReadable.asOpt$(JsReadable.scala:18)
	at play.api.libs.json.JsObject.asOpt(JsValue.scala:121)
	at org.mimirdb.lenses.implementation.TypeInferenceLens$.train(TypeInferenceLens.scala:17)
	at org.mimirdb.api.request.CreateLensRequest.handle(CreateLens.scala:43)
	at info.vizierdb.commands.mimir.LensCommand.process(LensCommand.scala:69)
	at info.vizierdb.commands.mimir.LensCommand.process$(LensCommand.scala:43)
	at info.vizierdb.commands.mimir.TypeInference$.process(TypeInference.scala:25)
	at info.vizierdb.viztrails.Scheduler$.processSynchronously(Scheduler.scala:245)
	at info.vizierdb.viztrails.Scheduler$WorkflowExecution.exec(Scheduler.scala:312)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by lordpretzel** [comment]
[casts.vizier.zip](https://github.com/VizierDB/vizier-scala/files/6674056/casts.vizier.zip)
