### ISSUE TITLE
Loading remote dataset fails with mimir-api v1.1

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/vizier-scala#111]
When loading a dataset from a remote source (Socrata), this fails in the 1.1 vizier-scala version. I've added some test cases to `mimir-api` to dig down. The test cases pass in `mimir-api` master, but fail the `1.1` branch:

``` scala
  "Load CSV files from socrata data portal" >> {

    val request = LoadRequest(
                    file                   = "https://data.cityofchicago.org/resource/we8h-apcf.csv",
                    format                 = "csv",
                    inferTypes             = true,
                    detectHeaders          = true,
                    humanReadableName      = Some("ChicagoMurals"),
                    backendOption          = Seq(),
                    dependencies           = Some(Seq()),
                    resultName             = None,
                    properties             = None,
                    proposedSchema         = None,
                    urlIsRelativeToDataDir = Some(false),
                  )
    val response = Json.toJson(request.handle).as[CreateResponse]

    val df = MimirAPI.catalog.get(response.name)
    df.schema must haveSize(16)
    df.schema.fields(0) must beEqualTo(StructField("mural_registration_id", ShortType))
  }

  "Load JSON files from socrata data portal" >> {

    val request = LoadRequest(
                    file                   = "https://data.cityofchicago.org/resource/we8h-apcf.json",
                    format                 = "csv",
                    inferTypes             = false,
                    detectHeaders          = false,
                    humanReadableName      = Some("ChicagoMuralsJSON"),
                    backendOption          = Seq(),
                    dependencies           = Some(Seq()),
                    resultName             = None,
                    properties             = None,
                    proposedSchema         = None,
                    urlIsRelativeToDataDir = Some(false),
                  )
    val response = Json.toJson(request.handle).as[CreateResponse]

    val df = MimirAPI.catalog.get(response.name)
    df.schema must haveSize(20)
  }
```

failing to locate the downloaded file:

``` shell
[error] ! Load CSV files from socrata data portal
[error]  org.apache.spark.sql.AnalysisException: Path does not exist: file:/Users/lord_pretzel/Documents/workspace/mimir-api/vizier_downloads/DATASOURCEChicagoMurals1573778298-VN6WFl4Flr.csv; (DataSource.scala:764)
[error] org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:764)
[error] org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:751)
[error] org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:580)
[error] org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:405)
[error] org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
[error] org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
[error] org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
[error] org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:232)
[error] org.mimirdb.data.LoadConstructor.loadCSVWithCaveats(LoadConstructor.scala:191)
[error] org.mimirdb.data.LoadConstructor.construct(LoadConstructor.scala:48)
[error] org.mimirdb.data.Catalog.put(Catalog.scala:218)
[error] org.mimirdb.api.request.LoadRequest.handle(Load.scala:136)
[error] org.mimirdb.api.request.LoadSpec.$anonfun$new$41(LoadSpec.scala:194)
```

**Comment by okennedy** [comment]
@lordpretzel , just to confirm: The v1.1 branch of mimir-api is stale and needs to be deleted.  I've been pushing 1.1 changes to master (tagged 1.1-SNAPSHOT).  If it works on master then we're good.

As an aside, could you please push the test cases?

**Comment by lordpretzel** [comment]
The client facing error is:

```
10:27:52.029 [ForkJoinPool-1-worker-11] TRACE info.vizierdb.viztrails.Scheduler$ - About to Process [Load Dataset](name: chicagomurals, loadOptions: , loadDataSourceErrors: false, schema: , loadDetectHeaders: true, file: <unknown file> @ url 'https://data.cityofchicago.org/resource/we8h-apcf.csv', loadInferTypes: false, loadFormat: csv) <- (SCOPE: {  })
org.mimirdb.api.FormattedError
	at org.mimirdb.api.FormattedError$.apply(FormattedError.scala:12)
	at org.mimirdb.api.request.LoadRequest.handle(Load.scala:145)
	at info.vizierdb.commands.data.LoadDataset$.process(LoadDataset.scala:113)
	at info.vizierdb.viztrails.Scheduler$.processSynchronously(Scheduler.scala:314)
	at info.vizierdb.viztrails.Scheduler$WorkflowExecution.exec(Scheduler.scala:382)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by lordpretzel** [comment]
It's pushed to branch `new_remote_load_tests`

**Comment by okennedy** [comment]
This looks like an issue with Staging putting files in the wrong place.
