### ISSUE TITLE
Creating cell fails when following cell is a Temporary Cell

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#157]
**Describe the bug**
Creating a new cell at the end of a workflow in Vizier 2.0 fails when the following cell is a temporary cell. 

**To Reproduce**
1. In Vizier 2.0, create a new project
2. Create a new cell (e.g., load dataset), but do not hit "Save" yet
3. Create another new cell at the end of the workflow.  Do not hit "Save" on that one either
4. Hit "Save" on the first cell.

The backend reports:
```
14:53:33.270 [qtp1856400435-125] WARN  i.v.a.websocket.BranchWatcherSocket - Websocket error: {}
info.vizierdb.api.response.ErrorResponse: NoSuchEntityResponse()
	at info.vizierdb.api.response.ErrorResponse$.noSuchEntity(ErrorResponse.scala:10)
	at info.vizierdb.api.InsertModule$.$anonfun$apply$3(InsertModule.scala:51)
	at scala.Option.getOrElse(Option.scala:189)
	at info.vizierdb.api.InsertModule$.$anonfun$apply$1(InsertModule.scala:51)
	at scalikejdbc.DBConnection.autoCommit(DBConnection.scala:264)
	at scalikejdbc.DBConnection.autoCommit$(DBConnection.scala:262)
	at scalikejdbc.DB.autoCommit(DB.scala:60)
	at scalikejdbc.DB$.$anonfun$autoCommit$1(DB.scala:244)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:23)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:21)
	at scalikejdbc.DB$.using(DB.scala:140)
	at scalikejdbc.DB$.autoCommit(DB.scala:241)
	at info.vizierdb.api.InsertModule$.apply(InsertModule.scala:44)
	at info.vizierdb.api.websocket.BranchWatcherAPIRoutes.route(BranchWatcherAPIRoutes.scala:28)
	at info.vizierdb.api.websocket.BranchWatcherSocket$Router$.route(BranchWatcherSocket.scala:190)
	at info.vizierdb.api.websocket.BranchWatcherSocket.$anonfun$onText$1(BranchWatcherSocket.scala:106)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```

**Expected behavior**
The cell is added successfully.

**Environment (please complete the following information):**

OS: 
```
Linux agamemnon 5.15.11-76051511-generic #202112220937~1640185481~21.10~b3a2c21 SMP Wed Dec 22 15:41:49 U x86_64 x86_64 x86_64 GNU/Linux
```
Browser: Firefox
Java version: Java 11
Vizier version: 2.0

**Additional context**

**Comment by okennedy** [comment]
Closed along with #196
