### ISSUE TITLE
UI crashes when creating a new cell while code is executing

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#6]
With Firefox 80.0.1, creating and/or editing a cell while downstream cells are running appears to crash the browser tab with a "A script on this page is causing it to run slow".

**Comment by okennedy** [comment]
Repro:
1. Create a new python cell:
```
from time import sleep
sleep(100)
```
2. While the cell is running, add another cell (e.g., SQL `SELECT * FROM range(1, 10)`)

Looks like this is a backend bug... the scheduler's planning components are missing a few cases.
```
scala.MatchError: RUNNING (of class scala.Enumeration$Val)
	at info.vizierdb.viztrails.Provenance$.$anonfun$updateCellStates$1(Provenance.scala:136)
	at info.vizierdb.viztrails.Provenance$.$anonfun$updateCellStates$1$adapted(Provenance.scala:134)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at info.vizierdb.viztrails.Provenance$.updateCellStates(Provenance.scala:134)
	at info.vizierdb.viztrails.Scheduler$WorkflowExecution.$anonfun$exec$1(Scheduler.scala:366)
	at info.vizierdb.viztrails.Scheduler$WorkflowExecution.$anonfun$exec$1$adapted(Scheduler.scala:365)
	at scalikejdbc.DBConnection.autoCommit(DBConnection.scala:242)
	at scalikejdbc.DBConnection.autoCommit$(DBConnection.scala:240)
	at scalikejdbc.DB.autoCommit(DB.scala:60)
	at scalikejdbc.DB$.$anonfun$autoCommit$1(DB.scala:216)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:22)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:20)
	at scalikejdbc.DB$.using(DB.scala:139)
	at scalikejdbc.DB$.autoCommit(DB.scala:215)
	at info.vizierdb.viztrails.Scheduler$WorkflowExecution.exec(Scheduler.scala:365)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by okennedy** [comment]
This bug was the result of a state management system that had not been properly formalized.  The oversight has been [rectified](https://github.com/VizierDB/vizier-scala/wiki/DevGuide-CellStates), and this appears to work now.
