### ISSUE TITLE
Binding error when listing caveats

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#90]
Caveats in post-aggregate queries (maybe with UNIONs?) show the following.  It looks like some variable is not getting the proper expression ID.

```
1:55:00.234 [Executor task launch worker for task 66305] ERROR org.apache.spark.executor.Executor - Exception in task 0.0 in stage 1973.0 (TID 66305)
org.apache.spark.sql.catalyst.errors.package$TreeNodeException: Binding attribute, tree: LHS___MIMIR_ROWID#414987L
	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)
	at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1.applyOrElse(BoundAttribute.scala:75)
	at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1.applyOrElse(BoundAttribute.scala:74)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$1(TreeNode.scala:309)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:72)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:309)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$3(TreeNode.scala:314)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChild$2(TreeNode.scala:368)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$4(TreeNode.scala:427)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
	at scala.collection.immutable.List.map(List.scala:305)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:427)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:397)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:350)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:314)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$3(TreeNode.scala:314)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChild$2(TreeNode.scala:368)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$4(TreeNode.scala:427)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
....
Caused by: java.lang.RuntimeException: Couldn't find LHS___MIMIR_ROWID#414938L in [value#331,__MIMIR_ROWID#414892L,RHS___MIMIR_ROWID#415189L]
```

**Comment by okennedy** [comment]
The rabbit hole keeps getting deeper.  

From the looks of it, Scala's `isnull` operator transparently replaces itself with a `coalesce` (makes sense, the semantics are equivalent).  However, the way it does this is by adding the `coalesce` as a child, while preserving its `left` and `right` arguments (which are used for display purposes; hiding the `coalesce` in the `child` field).  I have no clue how this is happening, but it seems like the `coalesce` descendent is falling out of sync with the `left` and `right` descendents.

More digging is called for.

**Comment by okennedy** [comment]
I have a consistent reproduction: 

```
SELECT * FROM 
R.csv LEFT OUTER JOIN S.csv LEFT OUTER JOIN S.csv
```

The problem appears to be that `EXISTS` is not reentrant.  Take the following expression:
```
Exists(Q1, Seq(
  Exists(Q2, Seq(expr)
))
```
Attributes from Q1 are not visible to `expr`.  This is a problem for mimir-caveats' EnumeratePlanCaveats, which uses `Exists` to push down join conditions.  Simply put, this bug will arise any time we try to enumerate a caveat applied below two or more join operators.

**Comment by okennedy** [comment]
As of https://github.com/UBOdin/mimir-caveats/commit/4e888ca1622a586b23a46a01986f39250e24fc34 this should now be fixed.
