### ISSUE TITLE
Python Arrow integration breaks on some installs

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#92]
I've been trying to track this down.  

On PopOS 20.10 (based on Ubuntu 20.10) w/ Java 8 installed, python arrow works as expected

On Debian 10 w/ Java 11 installed, attempting to use Arrow breaks. When allocating the Arrow dataframe, the scala-side produces the following error.  Following this the python-side attempts to read the dataframe, and `_load_from_socket` returns an empty list.

My current suspicion is that this is a Java 11 issue, in which case fixing it will likely require bringing Vizier up to a more recent version of Spark.

```
12:01:19.220 [Executor task launch worker for task 2473] ERROR org.apache.spark.TaskContextImpl - Error in TaskCompletionListener
java.lang.IllegalStateException: Memory was leaked by query. Memory leaked: (32768)
Allocator(toBatchIterator) 0/32768/32768/9223372036854775807 (res/actual/peak/limit)

	at org.apache.arrow.memory.BaseAllocator.close(BaseAllocator.java:464)
	at org.apache.spark.sql.execution.arrow.ArrowConverters$.$anonfun$toBatchIterator$1(ArrowConverters.scala:94)
	at org.apache.spark.sql.execution.arrow.ArrowConverters$.$anonfun$toBatchIterator$1$adapted(ArrowConverters.scala:92)
	at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:125)
	at org.apache.spark.TaskContextImpl.$anonfun$markTaskCompleted$1(TaskContextImpl.scala:124)
	at org.apache.spark.TaskContextImpl.$anonfun$markTaskCompleted$1$adapted(TaskContextImpl.scala:124)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1(TaskContextImpl.scala:137)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1$adapted(TaskContextImpl.scala:135)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:135)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
	at org.apache.spark.scheduler.Task.run(Task.scala:137)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
...
Previous exception in task: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
	io.netty.util.internal.PlatformDependent.directBuffer(PlatformDependent.java:490)
	io.netty.buffer.NettyArrowBuf.getDirectBuffer(NettyArrowBuf.java:243)
	io.netty.buffer.NettyArrowBuf.nioBuffer(NettyArrowBuf.java:233)
	io.netty.buffer.ArrowBuf.nioBuffer(ArrowBuf.java:245)
	org.apache.arrow.vector.ipc.message.ArrowRecordBatch.computeBodyLength(ArrowRecordBatch.java:222)
	org.apache.arrow.vector.ipc.message.MessageSerializer.serialize(MessageSerializer.java:240)
	org.apache.arrow.vector.ipc.message.MessageSerializer.serialize(MessageSerializer.java:226)
	org.apache.spark.sql.execution.arrow.ArrowConverters$$anon$1.$anonfun$next$1(ArrowConverters.scala:118)
	scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	org.apache.spark.sql.execution.arrow.ArrowConverters$$anon$1.next(ArrowConverters.scala:121)
	org.apache.spark.sql.execution.arrow.ArrowConverters$$anon$1.next(ArrowConverters.scala:97)
	scala.collection.Iterator.foreach(Iterator.scala:943)
	scala.collection.Iterator.foreach$(Iterator.scala:943)
	org.apache.spark.sql.execution.arrow.ArrowConverters$$anon$1.foreach(ArrowConverters.scala:97)
	scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	scala.collection.TraversableOnce.to(TraversableOnce.scala:348)
	scala.collection.TraversableOnce.to$(TraversableOnce.scala:346)
```

**Comment by okennedy** [comment]
A spark version bump has a huge potential to turn into a rathole.  Leaving this bug off to 1.2 and adding a java version check into mimir-api to produce a sane error message if the user is running java 1.9+

**Comment by okennedy** [comment]
Depends on #103

**Comment by okennedy** [comment]
Vizier 2.0 migrates to Spark 3.2, which should (hopefully?) resolve this issue.

**Comment by okennedy** [comment]
Confirmed.  This issue is no longer a problem on Java 11.

See #179 ; Deferring Java 18 checks to v2.1
